import 'package:flutter/foundation.dart';

@immutable
class SteelxTank {
  final String model;
  final int litres;

  final int diameter, height;
  final int? manholeDiameter;

  final int? stand, legs;

  final double? inlet, outlet, thickness, drain;

  final bool isHorizontal;

  const SteelxTank(
    this.model, {
    required this.litres,
    required this.diameter,
    required this.height,
    this.manholeDiameter,
    this.stand,
    this.legs,
    this.inlet,
    this.outlet,
    this.thickness,
    this.drain,
    this.isHorizontal = false,
  });

  static List<SteelxTank> allTanks = [
    SteelxTank(
      'SX25',
      litres: 250,
      diameter: 700,
      height: 960,
      manholeDiameter: 420,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
    ),
    SteelxTank(
      'SXG250L',
      litres: 250,
      diameter: 760,
      height: 960,
      stand: 320,
      legs: 3,
    ),
    SteelxTank(
      'SX50',
      litres: 500,
      diameter: 700,
      height: 1450,
      manholeDiameter: 420,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
    ),
    SteelxTank(
      'SXG500L',
      litres: 500,
      diameter: 760,
      height: 1450,
      stand: 320,
      legs: 3,
    ),
    SteelxTank(
      'SX100',
      litres: 1000,
      diameter: 970,
      height: 1760,
      manholeDiameter: 420,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
    ),
    SteelxTank(
      'SXG1000L',
      litres: 1000,
      diameter: 1030,
      height: 1760,
      stand: 320,
      legs: 3,
    ),
    SteelxTank(
      'SX150',
      litres: 1500,
      diameter: 1230,
      height: 2325,
      manholeDiameter: 420,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
    ),
    SteelxTank(
      'SXG1500L',
      litres: 1500,
      diameter: 1030,
      height: 2325,
      stand: 320,
      legs: 4,
    ),
    SteelxTank(
      'SX200',
      litres: 2000,
      diameter: 1420,
      height: 2355,
      manholeDiameter: 530,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
    ),
    SteelxTank(
      'SXG2000L',
      litres: 2000,
      diameter: 1480,
      height: 2055,
      stand: 485,
      legs: 4,
    ),
    SteelxTank(
      'SXG2500L',
      litres: 2500,
      diameter: 1480,
      height: 2365,
      stand: 485,
      legs: 4,
    ),
    SteelxTank(
      'SX300',
      litres: 3000,
      diameter: 1420,
      height: 2365,
      manholeDiameter: 530,
      inlet: 1,
      outlet: 2,
      thickness: 0.8,
      drain: 1,
    ),
    SteelxTank(
      'SXG3000L',
      litres: 3000,
      diameter: 1480,
      height: 2575,
      stand: 485,
      legs: 6,
    ),
    SteelxTank(
      'SX400',
      litres: 4000,
      diameter: 1700,
      height: 2575,
      manholeDiameter: 530,
      inlet: 2,
      outlet: 2,
      thickness: 0.8,
      drain: 1,
    ),
    SteelxTank(
      'SXG4000L',
      litres: 4000,
      diameter: 1720,
      height: 2150,
      stand: 485,
      legs: 8,
    ),
    SteelxTank(
      'SX500',
      litres: 5000,
      diameter: 1700,
      height: 2600,
      manholeDiameter: 700,
      inlet: 2,
      outlet: 2,
      thickness: 0.8,
      drain: 1,
    ),
    SteelxTank(
      'SXG5000L',
      litres: 5000,
      diameter: 1720,
      height: 2600,
      stand: 485,
      legs: 8,
    ),
    SteelxTank(
      'SXH10',
      litres: 1000,
      diameter: 1600,
      height: 160,
      manholeDiameter: 420,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
      isHorizontal: true,
    ),
    SteelxTank(
      'SXH15',
      litres: 1500,
      diameter: 1650,
      height: 160,
      manholeDiameter: 420,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
      isHorizontal: true,
    ),
    SteelxTank(
      'SXH20',
      litres: 2000,
      diameter: 1700,
      height: 160,
      manholeDiameter: 530,
      inlet: 1,
      outlet: 2,
      thickness: 0.6,
      drain: 1,
      isHorizontal: true,
    ),
  ]..sort((a, b) => a.litres.compareTo(b.litres));
}
