name: Deploy to Firebase Hosting

"on":
  push:
    branches:
      - main

env:
  flutter_version: "2.0.3"
  java_version: "12.x"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK (cached)
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable

      - name: Flutter Build (Web)
        run: |
          flutter config --enable-web
          flutter build web --web-renderer canvaskit --tree-shake-icons

      - name: Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOME_SOLUTIONS_7A714 }}"
          projectId: home-solutions-7a714
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
